Implement noshow result
PennyDreadfulMTG/gatherling_fork pull request #132
Opened 2018-08-28 14:02 UTC by stash86

Add extra codes to diferentiate normal win and noshow win, and let player to report noshow

Fixes #27

2018-09-06 03:40 UTC, silasary requested changes

2018-09-06 03:40 UTC, silasary commented on deck.php
> +                $res = 'Win'.($match->result == 'WO' ? ' Noshow' : '');
Can we use `NS` rather than WO?

2018-09-06 03:40 UTC, silasary commented on event.php
> +                $matchresult = '<span style="font-size: 14pt" title ="Opponent doesn\'t show up">&#x26A0;</span> W ';
"Opponent didn't show up"

2018-09-06 03:41 UTC, silasary commented
I'm also concerned that this will give TOs the impression that Gatherling will automatically handle NoShows, when in fact they still require manual intervention.

2018-09-06 03:55 UTC, stash86 commented
Well, TO does have to manually enters the "NS" result. And we can add automatic drop in the code for NS player, which only fires after TO input the result from Host CP

2018-09-06 03:56 UTC, stash86 commented on deck.php
> +                $res = 'Win'.($match->result == 'WO' ? ' Noshow' : '');
Yes we can

2018-09-08 01:04 UTC, TravisBuddy commented
Hey @stash86, 
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

2018-09-08 01:11 UTC, stash86 commented
Changed all 'WO' into 'NS'. Now I'm gonna add auto-drop for NS player, unless we are afraid of any player abuse (which I personally think there is no hole to be abused)

2018-09-09 05:00 UTC, silasary commented
I don't want auto-drop.  We have had cases of people accidentally reporting No-Shows early, and then their opponent showing up.

And that's not even considering the case of someone getting salty and dropping their opponent out of spite.

2018-09-10 03:54 UTC, stash86 commented
So let's say player A reports their match as a NS win. Based on my proposed code, there are 4 cases that can happens (I haven't work on the auto-drop code yet)

1. Player B later on reports their side of result as a 0-2 loss. The NS tag will be removed. (The auto-drop function won't be called)

2. Player A and player B later on play their match. And then Player B reports their side of actual result. When the result conflicted, the code will ask both players to enter the correct result. Once it happens, the NS tag will be removed. (The auto-drop function won't be called)

3. The host pushed the result through Event CP, but they reports it as a simple 2-0 win for Player A. The NS tag will be removed. (The auto-drop function won't be called)

4. The host pushed the result through Event CP, and they reports it as a NS 2-0 win for Player A. (The auto-drop function will be called)

2020-08-12 11:17 UTC, closed without merging