Use most recent event's Event Thread URL as Season Master Document
PennyDreadfulMTG/gatherling_fork pull request #235
Opened 2019-06-04 00:42 UTC by stash86

fixes #212

2019-07-11 13:04 UTC, silasary commented
This ignores the master document if it has been set.  What you want to do is check if the master document is null or empty, and do this replacement only in that case.

2019-07-11 13:05 UTC, silasary requested changes
This ignores the master document if it has been set. What you want to do is check if the master document is null or empty, and do this replacement only in that case.

2019-07-12 04:48 UTC, stash86 commented
Added the check

2019-07-12 04:56 UTC, silasary approved these changes

2019-07-12 05:00 UTC, merged